spring:
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect

  datasource:
    platform: h2
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:iam;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;Mode=Oracle
    username: sa
    password:

  flyway:
    enabled: true
    locations:
    - classpath:db/migration/dev
    - classpath:db/migration/fixture