spring:
  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
    generate-ddl: true
    properties:
      javax:
        persistence:
          schema-generation:
            create-source: metadata
            scripts:
              action: create
              create-target: create.sql